::_prog_start::  -- loop target
-- motion_check ADAPTED (rules: blend_radius_scaling): shorter adjacent segment 0.0mm × 0.25 = 0.0mm (< profile 12mm)
setSpeedJ(15)  -- 10% × max 150 deg/s = 15 deg/s (setSpeedJ is modal — re-emitted only when value changes)
movJ(p1)  -- step move_home  J5=+91.56°  joints=[-11.590, +14.460, +73.960, -3.760, +91.560, -37.350]
setDO(2,0)  -- step set_io DO2=0
-- motion_check ADAPTED (rules: awkward_wrist_transit): wrist Δ exceeds threshold — a cartesian movL with a spinning wrist is the worst of both worlds; forcing joint-space transit. linear predecessor: wrist Δ=30.2° > 30°
movJ(p2)  -- step move_linear (emitted movJ — columns-always-cartesian EXCEPTION: awkward_wrist_transit, see the ADAPTED line above)  derived_from='pick' offset_z_mm=100  (FIX C: SEEDED IK Δz=+100.00 mm; taught J5=+90.25° → emitted J5=+90.25° Δ0.000°)  joints=[+18.620, +7.235, +81.504, -3.931, +90.250, -7.171]  orient_dev=0.0001°  (D11 column-orientation-lock, max-axis of R_anchor·R_lifted^T)
setSpeedL(150)  -- 10% × max 1500 mm/s = 150 mm/s (setSpeedL is modal — re-emitted only when value changes)
movL(p3)  -- step move_linear  J5=+90.25°  joints=[+18.620, +7.810, +91.510, +6.650, +90.250, -7.170]  wrist_dev=max10.58° (J4Δ=10.58° J5Δ=0.00° J6Δ=0.00°) ≤ 15°
setDO(2,1)  -- step set_io DO2=1
wait(500)  -- step wait  duration_s=0.5 → 500 ms (wire-proven on v2.3, undocumented in luaenginelib; not waitCondition — that idiom hits 10006)
movL(p4)  -- step move_linear  derived_from='pick' offset_z_mm=100  (FIX C: SEEDED IK Δz=+100.00 mm; taught J5=+90.25° → emitted J5=+90.25° Δ0.000°)  joints=[+18.620, +7.235, +81.504, -3.931, +90.250, -7.171]  path_feas=ok worst=0.46° on J2 ≤ 60°  (columns-always-cartesian: ascent)  orient_dev=0.0001°  (D11 column-orientation-lock, max-axis of R_anchor·R_lifted^T)
-- motion_check ADAPTED (rules: awkward_wrist_transit): wrist Δ exceeds threshold — a cartesian movL with a spinning wrist is the worst of both worlds; forcing joint-space transit. linear predecessor: wrist Δ=48.3° > 30°
movJ(p5)  -- step move_linear (emitted movJ — columns-always-cartesian EXCEPTION: awkward_wrist_transit, see the ADAPTED line above)  derived_from='place' offset_z_mm=100  (FIX C: SEEDED IK Δz=+100.00 mm; taught J5=+90.25° → emitted J5=+90.25° Δ0.000°)  joints=[+18.620, +21.623, +115.213, +44.166, +90.250, -7.170]  orient_dev=0.0000°  (D11 column-orientation-lock, max-axis of R_anchor·R_lifted^T)
movL(p6)  -- step move_linear  J5=+90.25°  joints=[+18.620, +28.880, +118.770, +54.980, +90.250, -7.170]  wrist_dev=max10.81° (J4Δ=10.81° J5Δ=0.00° J6Δ=0.00°) ≤ 15°
setDO(2,0)  -- step set_io DO2=0
movL(p7)  -- step move_linear  derived_from='place' offset_z_mm=100  (FIX C: SEEDED IK Δz=+100.00 mm; taught J5=+90.25° → emitted J5=+90.25° Δ0.000°)  joints=[+18.620, +21.623, +115.213, +44.166, +90.250, -7.170]  path_feas=ok worst=0.61° on J2 ≤ 60°  (columns-always-cartesian: ascent)  orient_dev=0.0000°  (D11 column-orientation-lock, max-axis of R_anchor·R_lifted^T)
movJ(p8)  -- step move_home  J5=+91.56°  joints=[-11.590, +14.460, +73.960, -3.760, +91.560, -37.350]
goto _prog_start  -- step loop  continuous (count=0)

-- generated by estun_driver.program_ops from program 'test100'
-- taught steps: 13, requested speed_pct=10, operator_cap_pct=100, effective_pct=10
-- motion: profile=joint blend_preset='medium' radius_mm=12 descent_accel=normal max_dps=150 max_mmps=1500
-- codegen: git=4b11f53d5264 src_sha=fc369bb7fb7d src_mtime=2026-08-19T15:13:01 boot=2026-08-31T09:31:30
-- motion_check: 4 finding(s), 3 adaptation(s) applied (adaptations_switch=on)
--   [WARN] step 0 (Move to home position): [inconsistent_wrist_orientation] 5 taught-point pair(s) differ by more than 20° in wrist axes (max 58.7°) — inconsistent wrist orientations across the program
--   [ADAPTED] step 0 (Move to home position): [blend_radius_scaling] blend radius scaled to 0.0mm (profile 12mm capped by 25% × shorter segment 0.0mm)
--   [ADAPTED] step 2 (Approach above pick): [awkward_wrist_transit] wrist Δ exceeds 30° threshold (linear Δ=30.2°) — forcing motion_profile=joint for this transit
--   [ADAPTED] step 7 (Approach above place): [awkward_wrist_transit] wrist Δ exceeds 30° threshold (linear Δ=48.3°) — forcing motion_profile=joint for this transit
-- payload: UNSET — collision-detection accuracy on this program is reduced until an operator sets the tool mass in the program editor
-- line_map (D9 · one entry per step, {step_idx, step_id, action, lua_line_start, lua_line_end}): [{"step_idx":0,"step_id":1,"action":"move_home","lua_line_start":1,"lua_line_end":3},{"step_idx":1,"step_id":2,"action":"set_io","lua_line_start":4,"lua_line_end":4},{"step_idx":2,"step_id":3,"action":"move_linear","lua_line_start":5,"lua_line_end":6},{"step_idx":3,"step_id":4,"action":"move_linear","lua_line_start":7,"lua_line_end":8},{"step_idx":4,"step_id":5,"action":"set_io","lua_line_start":9,"lua_line_end":9},{"step_idx":5,"step_id":6,"action":"wait","lua_line_start":10,"lua_line_end":10},{"step_idx":6,"step_id":7,"action":"move_linear","lua_line_start":11,"lua_line_end":11},{"step_idx":7,"step_id":8,"action":"move_linear","lua_line_start":12,"lua_line_end":13},{"step_idx":8,"step_id":9,"action":"move_linear","lua_line_start":14,"lua_line_end":14},{"step_idx":9,"step_id":10,"action":"set_io","lua_line_start":15,"lua_line_end":15},{"step_idx":10,"step_id":11,"action":"move_linear","lua_line_start":16,"lua_line_end":16},{"step_idx":11,"step_id":12,"action":"move_home","lua_line_start":17,"lua_line_end":17},{"step_idx":12,"step_id":13,"action":"loop","lua_line_start":18,"lua_line_end":19}]
-- lint: OK (0 findings against luaenginelib.json, 168 verbs)
--Lua version 5.3 time:2026-08-31 10:56:44
