"""Auto-generated by scripts/generate_lua_regression_corpus.py.
Do NOT hand-edit — regenerate by rerunning the script whenever
program_ops._KNOWN_BAD_PATTERNS changes.

Corpus provenance: every entry cites its origin
(program_ops.py:LINE + addendum-N §M). See lua_regression_corpus.json.
"""
import json
import pathlib
import sys

import pytest

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parents[2]))
from estun_driver.program_ops import lint_lua_source

CORPUS = json.loads((pathlib.Path(__file__).parent /
                     "lua_regression_corpus.json").read_text())

# Skip un-encoded historical entries — those are a queue for
# future matcher additions; they cannot yet run through
# lint_lua_source because there's no matcher to trigger.
AUTO_DERIVED = [e for e in CORPUS if e.get("kind") == "auto_derived"]
HAND_QUEUED  = [e for e in CORPUS if e.get("kind") == "un_encoded_historical"]


def _build_lua(verb, args):
    call = f"{verb}({', '.join(args)})"
    if verb in ("getDI", "getDO", "getAI", "getAO", "waitCondition"):
        return f"local _ = {call}\n"
    return f"{call}\n"


@pytest.mark.parametrize("entry",
                         AUTO_DERIVED,
                         ids=[e["name"] for e in AUTO_DERIVED])
def test_corpus_entry(entry):
    lua = _build_lua(entry["verb"], entry["args"])
    findings = lint_lua_source(lua)
    if entry["expected"] == "accept":
        assert findings == [], (
            f"{entry['name']}: expected accept, got findings "
            f"{[f['reason'] for f in findings]!r}. Origin: "
            f"{entry['origin']}"
        )
    else:
        assert findings, (
            f"{entry['name']}: expected REJECT, got accept. "
            f"Matcher {entry['origin']} did not fire on lua={lua!r}"
        )
        substr = entry.get("reject_reason_substr")
        if substr:
            joined = " || ".join(f["reason"] for f in findings)
            assert substr.lower() in joined.lower(), (
                f"{entry['name']}: reject fired, but no finding "
                f"contained {substr!r}. Got: {joined!r}"
            )


def test_hand_queued_present():
    """Un-encoded historical incidents MUST remain in the corpus as
    a visible queue for future matcher additions. This test fails
    loud if someone deletes them without landing the matcher.

    An entry can be in one of two states:
      - stage='semantic_round_trip_queue'  — matcher NOT yet encoded
      - stage='semantic_round_trip'        — matcher encoded, entry
        preserved for provenance/audit trail
    """
    names = {e["name"] for e in HAND_QUEUED}
    assert "palletize-transit-over-slot-unreachable" in names
    assert "multi-pair-role-map-anchor-mixup" in names
    for e in HAND_QUEUED:
        assert e["stage"] in ("semantic_round_trip_queue",
                              "semantic_round_trip")
        assert "grep-verified" in e["origin"]
