"""Codegen tests for the counted-cycle loop behavior.

Locks in the three regimes:
  count == 0  → continuous, emits `goto _prog_start` + label prefix
  count == 1  → no-op emitted; body Lua must be byte-identical to a
                program with the loop step stripped entirely
  count >= 2  → body wrapped in `for i=1,N do ... end`; initial
                move_home stays OUTSIDE the loop, trailing return-to-
                home + body live inside.

`for` and `end` are plain Lua 5.3 syntax — no controller verb was
invented — so no wire capture is required. This module deliberately
exercises the codegen only; the executor path is untouched.
"""

from __future__ import annotations

import copy

from estun_driver.program_ops import codegen_lua_from_program


def _base_program():
    """A minimal 4-step program that exercises every loop-relevant
    branch: initial move_home, two body moves, return-to-home. Points
    carry only what codegen needs (taught_joints), keeping the fixture
    readable and independent of the real testwizard.json on disk."""
    return {
        'id': 'cycles-test',
        'name': 'cycles-test',
        'config': {},
        'steps': [
            {'action': 'move_home',   'label': 'Move to home',
             'taught_joints': [0.0] * 6, 'position_role': 'home'},
            {'action': 'move_linear', 'label': 'Pick contact',
             'taught_joints': [10.0, 0, 0, 0, 0, 0], 'position_role': 'pick'},
            {'action': 'move_linear', 'label': 'Place contact',
             'taught_joints': [-10.0, 0, 0, 0, 0, 0], 'position_role': 'place'},
            {'action': 'move_home',   'label': 'Return to home',
             'taught_joints': [0.0] * 6, 'position_role': 'home'},
        ],
        'points': {},
    }


def _lua_body(lua: str):
    """Strip footer/header comments to compare bodies without a build
    timestamp getting in the way."""
    return [
        ln for ln in lua.splitlines()
        if not ln.startswith('--Lua version')
        and not ln.startswith('-- generated by')
        and not ln.startswith('-- taught steps:')
        and not ln.startswith('-- payload:')
        # D9 line_map stamp (2026-08-03) — carries one entry per
        # step, so a count=1 loop program has an extra entry vs the
        # bare version. That is the point of D9; it's not part of
        # the byte-for-byte body invariant.
        and not ln.startswith('-- line_map (D9')
    ]


def test_count_1_matches_no_loop_step_output_byte_for_byte():
    """count=1 emits a single no-op comment and nothing else. The rest
    of the body must be byte-identical to the same program with no
    loop step at all — the acceptance criterion for the run-once
    equivalent."""
    prog_bare = _base_program()
    prog_1    = _base_program()
    prog_1['steps'].append({'action': 'loop', 'goto': 1, 'count': 1})

    lua_bare, _, _ = codegen_lua_from_program(prog_bare, operator_speed_limit_pct=65)
    lua_1,    _, _ = codegen_lua_from_program(prog_1,    operator_speed_limit_pct=65)
    # Strip the count=1 no-op comment; everything else must match.
    body_1 = [ln for ln in _lua_body(lua_1) if 'count=1' not in ln]
    assert body_1 == _lua_body(lua_bare)


def test_count_gte_2_wraps_body_in_for_loop_home_outside():
    """count=3 emits `for i=1,3 do` right AFTER the initial move_home
    and `end` at the loop step. The initial home stays outside; the
    trailing return-to-home lives inside so each cycle ends safe.

    After the 2026-07-29 motion-vocabulary work, setSpeedJ/setSpeedL
    modal preludes precede the first movJ/movL respectively — the
    relative ordering of move_home, for-loop opener, and closing
    `end` is what this test enforces, not the absolute file-line-1
    position of movJ."""
    prog = _base_program()
    prog['steps'].append({'action': 'loop', 'goto': 1, 'count': 3})
    lua, _, _ = codegen_lua_from_program(prog, operator_speed_limit_pct=65)
    body = _lua_body(lua)
    # First motion emission is the initial move_home (movJ).  A
    # setSpeedJ(N) prelude line may precede it — that's the vocabulary
    # work's modal emission — but the FIRST movJ/movL line in the body
    # must be the initial home.
    move_lines = [i for i, ln in enumerate(body)
                  if ln.startswith('movJ(') or ln.startswith('movL(')]
    assert move_lines, body
    assert 'move_home' in body[move_lines[0]], body[move_lines[0]]
    # Two move_home lines emitted (initial + return). The second one
    # sits INSIDE the loop — the `end` line comes after it.
    home_idxs = [i for i, ln in enumerate(body) if 'move_home' in ln
                 and (ln.startswith('movJ(') or ln.startswith('movL('))]
    assert len(home_idxs) == 2, home_idxs
    end_lines = [i for i, ln in enumerate(body) if ln.strip().startswith('end')]
    assert end_lines, 'end line missing'
    # Initial home is before the `for` opener; return-home is between
    # the `for` and the `end`.
    for_lines = [i for i, ln in enumerate(body) if ln.strip().startswith('for i=')]
    assert for_lines
    assert home_idxs[0] < for_lines[0], 'initial home must be OUTSIDE the loop'
    assert home_idxs[1] > for_lines[0], 'return home must be INSIDE the loop'
    assert home_idxs[1] < end_lines[-1], 'return home must precede the `end`'


def test_count_0_stays_on_continuous_goto():
    """The wire-verified continuous path is unchanged: label prefix +
    `goto _prog_start` at the loop step."""
    prog = _base_program()
    prog['steps'].append({'action': 'loop', 'goto': 1, 'count': 0})
    lua, _, _ = codegen_lua_from_program(prog, operator_speed_limit_pct=65)
    body = _lua_body(lua)
    assert body[0].startswith('::_prog_start::'), body[0]
    assert any('goto _prog_start' in ln for ln in body)
    # No for/end lines for the continuous path.
    assert not any(ln.strip().startswith('for i=') for ln in body)
    assert not any(ln.strip() == 'end' for ln in body)


def test_finite_loop_never_emits_start_label():
    """The for-loop wrap replaces the goto-based skeleton entirely; no
    `::_prog_start::` label should appear."""
    prog = _base_program()
    prog['steps'].append({'action': 'loop', 'goto': 1, 'count': 5})
    lua, _, _ = codegen_lua_from_program(prog, operator_speed_limit_pct=65)
    assert '::_prog_start::' not in lua
