"""Program-execution helpers for the Estun driver.

Split into three concerns:

  1. Lua codegen — turns our taught-program IR (list of steps with
     6-joint `taught_joints`) into Lua 5.3 source that the controller
     will accept, plus a `varspoint` dict of named points.

  2. HTTP save — POSTs the source + points + registry entries to the
     controller's HTTP API (port 9198, `/api/robotcode/` +
     `/api/robotjson/`). Discovered from the factory UI bundle's
     `useProjectSave` composable.

  3. ProjectState / Error parsing — the frames the driver receives on
     `publish/ProjectState` and `publish/Error`; kept out of the driver
     node so unit tests can exercise the reflood-dedup logic without
     spinning up rclpy.

None of this touches ROS directly. The driver imports these helpers
and calls them from its own subscriber callbacks so the gate check
lives in one place.
"""
from __future__ import annotations

import json
import re as _re
import time
import urllib.error
import urllib.request
from typing import Any, Iterable


# ────────────────────────────────────────────────────────────────
# Lua codegen
# ────────────────────────────────────────────────────────────────

# The controller writes its own Lua files with a "--Lua version 5.3
# time:YYYY-MM-DD HH:MM:SS" trailer (seen on the demo project). We
# emit the same trailer so a round-trip select/update looks
# byte-similar and the operator can eyeball diffs.
_LUA_TRAILER_FMT = '--Lua version 5.3 time:%Y-%m-%d %H:%M:%S'


def _make_jp_point(joints: list[float], nm: str,
                   coord: int = 0, tool: int = 0) -> dict:
    """varspoint entry for a joint pose. The controller expects:
        {postype: "jp", nm: "<name>", val: <JSON-encoded string>}
    where val decodes to
        {coord, tool, jp: [j1..j6], ep: []}
    Mined from `useProjectPointJoint.newPoint` in the factory UI
    bundle — the first save attempt on this branch used a plain
    object under val and the controller rejected with
    10012 "Failed to parse variable <p1>: Value is not in JSON
    string format." because it tries JSON.parse(val).
    """
    val_obj = {
        'coord': int(coord),
        'tool': int(tool),
        'jp': [float(v) for v in joints],
        'ep': [],
    }
    return {
        'postype': 'jp',
        'nm': nm,
        'val': json.dumps(val_obj, separators=(',', ':')),
    }


def codegen_lua_from_program(
    program: dict,
    *,
    operator_speed_limit_pct: int,
    point_prefix: str = 'p',
) -> tuple[str, dict[str, dict], int]:
    """Turn a taught-program dict into (lua_source, varspoint, effective_pct).

    Only steps with 6-element `taught_joints` are emitted. Anything
    else is skipped with a comment so the operator sees the gap in
    the generated file.

    Speed selection: the program's own `config.speed_pct` (or the
    top-level `speed_pct`) is CAPPED at operator_speed_limit_pct.
    The cap is a hard limit — no matter what a program requests,
    the emitted `Robot/setAutoMoveRate` sits at or below the
    operator ceiling.

    Point entries follow the shape mined from the factory UI bundle
    (see _make_jp_point) — {postype:"jp", nm, val:<JSON string>}.
    """
    cfg = program.get('config') or {}
    requested_pct = int(
        cfg.get('speed_pct')
        or program.get('speed_pct')
        or 10  # conservative default
    )
    eff_pct = max(1, min(int(operator_speed_limit_pct), requested_pct))

    steps = program.get('steps') or []
    varspoint: dict[str, dict[str, list[float]]] = {}
    lines: list[str] = []
    lines.append(f'-- generated by estun_driver.program_ops '
                 f'from program {program.get("id","<unknown>")!r}')
    lines.append(f'-- taught steps: {len(steps)}, '
                 f'requested speed_pct={requested_pct}, '
                 f'operator_cap_pct={operator_speed_limit_pct}, '
                 f'effective_pct={eff_pct}')
    lines.append('')

    # Line numbering matters here: setStartLine + project/runStep act on
    # file-line numbers, and the demo project we validated shape against
    # had movJ at line 1. So we emit EXECUTABLE statements starting at
    # line 1 (with inline trailing `--` comments for review context)
    # and put the header/trailer AFTER, not before. That way rung 2's
    # `setStartLine 1` puts the interpreter exactly on `movJ(p1)`.
    #
    # Two step-source paths land at the same movJ output:
    #   1. program.points table + step.point_name  — the schema authored
    #      via /api/programs/{id}/points. Preferred; the point is a
    #      first-class reusable entity across steps.
    #   2. step.taught_joints (legacy PBD-draft path). Kept for backward
    #      compat; each such step gets its own auto-named point (p1,
    #      p2, ...) unique to that step.
    #
    # Points from path (1) are emitted into varspoint under their
    # AUTHORED names; path (2) uses point_prefix + index. If both a
    # point_name and taught_joints are present on the same step, the
    # named point wins (authored schema is authoritative).
    # Verb table verified against the controller's own
    # /webmodel/cocontrol/luaeditor/luaenginelib.json (captured in
    # data/estun_captures/estun_lua_io_v2_20260721.har). Every verb
    # emitted below is a key in that library with the exact spelling
    # shown here. Do NOT re-invent spellings — the interpreter rejects
    # unknown names with 10012-class errors before any move runs.
    #
    # Wire-verified verbs currently used:
    #   movJ(p, opts)            movJ($1,{v=..., a=..., b=..., ...})
    #   setDO(port, value)       setDO($1,$2)      port in [0, 17]
    #   setAO(port, value)       setAO($1,$2)      port in [0, 3]
    #
    # Wire-verified but not yet emitted (available for a future
    # DI-wait / DO-read step):
    #   val = getDI(port)        val = getDI($1)
    #   val = getDO(port)        val = getDO($1)
    #   val = getAI(port)        val = getAI($1)
    #   val = getAO(port)        val = getAO($1)
    #
    # Delay: the 168-entry library has NO plain sleep/wait/delay verb.
    # The only wait-shaped primitive is waitCondition(cond, timeout) —
    # timeout unit unverified. A `wait` step therefore stays SKIPPED in
    # the emitted Lua with an explanatory comment; the operator-side UI
    # continues to flag it as "pending capture" in StepPreviewPanel.
    program_points = program.get('points') or {}
    exec_lines: list[str] = []
    fallback_idx = 0
    used_named: set[str] = set()   # named points that got REFERENCED
    for step in steps:
        action = step.get('action', '?')

        # ---- DO / AO set — verified verbs setDO / setAO --------------
        if action == 'set_io':
            io_id = str(step.get('io_id') or '').strip()
            m = _re.match(r'^(DO|AO)(\d+)$', io_id, _re.IGNORECASE)
            if not m:
                # DI writes aren't supported by the library (getDI is a
                # reader; no setDI verb exists). System-reserved names
                # (modeSwitch etc.) also fall through here.
                exec_lines.append(f'-- skipped {action!r}: '
                                  f'io_id {io_id!r} is not a writable DO/AO '
                                  f'(DI is read-only per luaenginelib; '
                                  f'system-reserved ports rejected)')
                continue
            kind = m.group(1).upper()
            port = int(m.group(2))
            raw_v = step.get('value')
            if kind == 'DO':
                if raw_v is None:
                    exec_lines.append(f'-- skipped {action!r} {io_id!r}: '
                                      f'value missing')
                    continue
                # DO takes 0/1 — coerce truthy → 1, everything else → 0.
                v = 1 if int(bool(raw_v)) == 1 and raw_v not in (0, '0', False) else 0
                exec_lines.append(f'setDO({port},{v})  -- step {action} {io_id}={v}')
            else:  # AO
                try:
                    v_f = float(raw_v)
                except (TypeError, ValueError):
                    exec_lines.append(f'-- skipped {action!r} {io_id!r}: '
                                      f'AO value {raw_v!r} not numeric')
                    continue
                exec_lines.append(f'setAO({port},{v_f:g})  -- step {action} {io_id}={v_f:g}')
            continue

        # ---- Wait / delay — verb NOT confirmed -----------------------
        # See header comment: no plain sleep/wait/delay verb exists in
        # luaenginelib.json. Emit a comment so line accounting still
        # matches computeLineMap in the frontend (one line per step).
        if action == 'wait':
            dur = step.get('duration_s')
            exec_lines.append(f'-- skipped {action!r}: no delay verb '
                              f'confirmed in luaenginelib.json '
                              f'(duration_s={dur!r}); needs a save-shape '
                              f'capture of the factory UI Wait node to '
                              f'confirm waitCondition(false, N) semantics + '
                              f'timeout unit')
            continue

        # ---- Motion — movJ via point ref or inline taught_joints ----
        pn = step.get('point_name')
        if pn and pn in program_points:
            p = program_points[pn]
            j = p.get('joints') or p.get('jp')
            if not (isinstance(j, list) and len(j) == 6
                    and all(isinstance(v, (int, float)) for v in j)):
                exec_lines.append(f'-- skipped {action!r}: '
                                  f'point {pn!r} has no valid joints')
                continue
            if pn not in used_named:
                varspoint[pn] = _make_jp_point(j, pn)
                used_named.add(pn)
            joints_s = ', '.join(f'{float(v):+.3f}' for v in j)
            exec_lines.append(f'movJ({pn})  -- step {action}  point={pn}  '
                              f'joints=[{joints_s}]')
            continue
        taught = step.get('taught_joints')
        if not (isinstance(taught, list) and len(taught) == 6
                and all(isinstance(v, (int, float)) for v in taught)):
            exec_lines.append(f'-- skipped {action!r}: '
                              f'no point_name/points ref, no 6-el taught_joints '
                              f'(got {type(taught).__name__})')
            continue
        fallback_idx += 1
        name = f'{point_prefix}{fallback_idx}'
        while name in program_points or name in used_named:
            fallback_idx += 1
            name = f'{point_prefix}{fallback_idx}'
        varspoint[name] = _make_jp_point(taught, name)
        used_named.add(name)
        joints_s = ', '.join(f'{float(v):+.3f}' for v in taught)
        exec_lines.append(f'movJ({name})  -- step {action}  '
                          f'joints=[{joints_s}]')

    trailer = time.strftime(_LUA_TRAILER_FMT, time.localtime(time.time()))
    # Header AFTER the executable region so `setStartLine 1` lands on
    # the first movJ. The Estun controller doesn't care about position
    # of comments; they're stripped by the interpreter.
    footer_lines = [
        '',
        f'-- generated by estun_driver.program_ops from program '
        f'{program.get("id","<unknown>")!r}',
        f'-- taught steps: {len(steps)}, requested speed_pct={requested_pct}, '
        f'operator_cap_pct={operator_speed_limit_pct}, effective_pct={eff_pct}',
        trailer,
    ]
    # CRLF line endings match the controller's own-emitted files (see
    # projectlua_projectluademo/lua/taskluademo.lua as ground truth).
    source = '\r\n'.join(exec_lines + footer_lines) + '\r\n'
    return source, varspoint, eff_pct


# ────────────────────────────────────────────────────────────────
# HTTP save — controller endpoints
# ────────────────────────────────────────────────────────────────
#
# Endpoints discovered in the factory UI bundle's `useProjectSave`:
#
#   POST /api/robotcode/project<lang>_<prid>_<lang>/update/<tkid>/
#       body: raw Lua source text
#
#   POST /api/robotjson/project<lang>_<prid>/update/varspoint/
#       body: JSON dict {name → {joint:[...] | end:{...}}}
#
#   POST /api/robotjson/project<lang>_<prid>/update/project/
#       body: JSON dict {<tkid>: {nm, tk}, ...}   (task registry)
#
#   POST /api/robotjson/project<lang>/update/projectlist/
#       body: JSON dict {<prid>: {nm, posid, varid}, ...}   (project registry)
#
# The demo project's shapes (probed against 192.168.2.136:9198):
#
#   projectlist.json = {"projectluademo":{"nm":"lua-demo","posid":0,"varid":0}}
#   projectluademo/project.json = {"taskluademo":{"nm":"lua-main","tk":1}}
#   projectluademo/varspoint.json = {}        ← empty; this is why the
#                                                demo's movJ(p1) errored
#                                                with "invalid target point"
#   projectluademo/lua/taskluademo.lua       ← the Lua source
#
# `<lang>` = "lua" for B1. select-side is /api/.../select/... which we
# also use to read back the projectlist before rewriting it (so we
# don't clobber other projects registered on the controller).
#
# Response shape (from a live GET probe):
#   {"code": 909, "data": [{"name": "<path>", "content": "<string>"}]}
# We treat code == 909 as OK. Anything else is surfaced verbatim.

def _origin(robot_ip: str, port: int) -> str:
    return f'http://{robot_ip}:{port}'


def _http_request(method: str, url: str, body: bytes | None,
                  content_type: str, timeout_s: float
                  ) -> tuple[int, dict, bytes]:
    """Bare urllib POST/GET so the driver picks up no new pip deps.
    Returns (http_status, response_json_or_empty, raw_body).
    """
    req = urllib.request.Request(url, data=body, method=method)
    if body is not None:
        req.add_header('Content-Type', content_type)
    try:
        with urllib.request.urlopen(req, timeout=timeout_s) as resp:
            raw = resp.read()
            try:
                parsed = json.loads(raw.decode('utf-8'))
            except Exception:
                parsed = {}
            return resp.status, parsed, raw
    except urllib.error.HTTPError as e:
        raw = e.read() if hasattr(e, 'read') else b''
        try:
            parsed = json.loads(raw.decode('utf-8'))
        except Exception:
            parsed = {}
        return e.code, parsed, raw


def http_get_projectlist(robot_ip: str, port: int, lang: str = 'lua',
                         timeout_s: float = 3.0) -> dict:
    """Fetch the current projectlist so we can merge our entry into it."""
    url = f'{_origin(robot_ip, port)}/api/robotjson/project{lang}/select/projectlist/'
    status, parsed, _ = _http_request('GET', url, None, '', timeout_s)
    if status != 200:
        raise RuntimeError(f'projectlist GET returned HTTP {status}')
    if parsed.get('code') != 909:
        raise RuntimeError(f'projectlist GET code={parsed.get("code")}')
    data = parsed.get('data') or []
    if not data:
        return {}
    content = data[0].get('content')
    if isinstance(content, str):
        try:
            return json.loads(content)
        except Exception:
            return {}
    return content or {}


def http_post_json(robot_ip: str, port: int, path: str, obj: Any,
                   timeout_s: float = 3.0) -> tuple[int, dict, bytes]:
    """POST a JSON body to /api/robotjson/... — used for varspoint,
    project (task registry), projectlist, varsproject."""
    url = f'{_origin(robot_ip, port)}{path}'
    body = json.dumps(obj, separators=(',', ':')).encode('utf-8')
    return _http_request('POST', url, body, 'application/json', timeout_s)


def http_post_text(robot_ip: str, port: int, path: str, text: str,
                   timeout_s: float = 3.0) -> tuple[int, dict, bytes]:
    """POST a Lua source body to /api/robotcode/... — the demo file
    uses text/plain; the controller doesn't seem to care about the
    charset param but text/plain is what apiPost uses in the bundle."""
    url = f'{_origin(robot_ip, port)}{path}'
    body = text.encode('utf-8')
    return _http_request('POST', url, body, 'text/plain; charset=utf-8', timeout_s)


def save_project(robot_ip: str, port: int, *,
                 project_id: str, task_id: str,
                 project_display: str, task_display: str,
                 lua_source: str,
                 varspoint: dict,
                 lang: str = 'lua',
                 timeout_s: float = 3.0) -> list[dict]:
    """Full save sequence.

    Order matters: source → varspoint → project.json → projectlist.
    The controller does not appear to depend on the order but running
    the point registration BEFORE registering the project keeps the
    controller from briefly seeing a project with no points.

    Returns a list of {step, path, http_status, code, body_head} dicts
    so a caller (the driver's /estun/program_status publisher or an
    ad-hoc test script) can log exactly what happened.
    """
    origin_ip = f'{_origin(robot_ip, port)}'  # for reporting
    steps: list[dict] = []

    def record(step, path, method, http_status, parsed, raw):
        body_head = raw[:180].decode('utf-8', 'replace') if raw else ''
        code = parsed.get('code') if isinstance(parsed, dict) else None
        steps.append({
            'step': step, 'path': path, 'method': method,
            'http_status': http_status, 'code': code,
            'body_head': body_head,
        })

    # 1) Lua source under /api/robotcode/
    p = f'/api/robotcode/project{lang}_{project_id}_{lang}/update/{task_id}/'
    st, parsed, raw = http_post_text(robot_ip, port, p, lua_source, timeout_s)
    record('source', p, 'POST', st, parsed, raw)

    # 2) varspoint dict under /api/robotjson/
    p = f'/api/robotjson/project{lang}_{project_id}/update/varspoint/'
    st, parsed, raw = http_post_json(robot_ip, port, p, varspoint, timeout_s)
    record('varspoint', p, 'POST', st, parsed, raw)

    # 3) project.json (task registry — one task in B1)
    project_json = {task_id: {'nm': task_display, 'tk': 1}}
    p = f'/api/robotjson/project{lang}_{project_id}/update/project/'
    st, parsed, raw = http_post_json(robot_ip, port, p, project_json, timeout_s)
    record('project', p, 'POST', st, parsed, raw)

    # 4) projectlist.json — MERGE our entry into whatever exists so
    #    other projects on the controller don't get clobbered. If the
    #    controller's projectlist is unreadable (rare), fall back to a
    #    single-entry rewrite; better to fail visibly if that too fails.
    try:
        current = http_get_projectlist(robot_ip, port, lang, timeout_s)
    except Exception as e:
        current = {}
        record('projectlist_get_warn', '', 'GET', 0, {}, str(e).encode())
    current[project_id] = {'nm': project_display, 'posid': 0, 'varid': 0}
    p = f'/api/robotjson/project{lang}/update/projectlist/'
    st, parsed, raw = http_post_json(robot_ip, port, p, current, timeout_s)
    record('projectlist', p, 'POST', st, parsed, raw)

    return steps


# ────────────────────────────────────────────────────────────────
# publish/ProjectState + publish/Error parsing
# ────────────────────────────────────────────────────────────────
#
# publish/ProjectState frames observed in the HAR (10 frames across
# three run cycles). Two distinct shapes for state==2:
#
#   {"id":"projectluademo","type":0,"state":2,"isStep":false}
#     ← first frame after project/run, carries the project id.
#
#   {"id":"","type":0,"state":2,"isStep":false,"scripts":{"taskA":{"line":N}}}
#     ← current-line frame; id blanks out, scripts.{task}.line is the
#       live program counter.
#
# The state==0 frame carries only {"id":"","type":0,"state":0,"isStep":false}
# — no scripts, no id. We keep our own last-known project id across
# the state=2→0 transition.
#
# publish/Error is a 3 Hz reflood (median 0.333 s inter-arrival in the
# HAR). Empty db (`[]`) is the "no active error" heartbeat. A non-empty
# entry is `[level, code, unix_ts, msg]` and the unix_ts stays CONSTANT
# across the entire reflood window for the same fault — that's what
# lets us dedup by (code, unix_ts).

def parse_project_state(db: Any, prev_id: str | None
                        ) -> tuple[dict, str | None]:
    """Return (status_dict, updated_prev_id). Caller keeps the id
    around and passes it in on the next frame."""
    if not isinstance(db, dict):
        return {}, prev_id
    state = int(db.get('state', 0))
    is_step = bool(db.get('isStep', False))
    scripts = db.get('scripts') or {}
    # Extract the (task, line) if present; there's normally exactly one
    # task in the scripts dict.
    task, line = None, None
    if isinstance(scripts, dict):
        for k, v in scripts.items():
            if not k or not isinstance(v, dict):
                continue
            task, line = k, int(v.get('line', 0))
            break
    project_id = db.get('id') or ''
    # Persist project id across the state=2 sequence — first frame
    # has it, subsequent frames blank it out.
    if project_id:
        new_prev = project_id
    else:
        new_prev = prev_id if state == 2 else None
    return {
        'state': state,
        'is_step': is_step,
        'task': task,
        'line': line,
        'project_id': new_prev,
    }, new_prev


class ErrorDedup:
    """Suppress the ~3 Hz publish/Error reflood.

    Dedup key: (code, unix_ts). unix_ts is the fault-time timestamp
    from the wire (element [2] of the entry), NOT the frame time — it
    stays constant across the reflood so identical faults collapse to
    one event. An empty db list is treated as a clear.
    """
    def __init__(self):
        self._active_key: tuple[int, float] | None = None
        self._active_entry: list | None = None

    def observe(self, db: Any) -> dict:
        """Return {kind, entry, key, changed}. kind ∈ {"clear", "new",
        "same"}."""
        if not isinstance(db, list) or len(db) == 0:
            changed = self._active_key is not None
            self._active_key = None
            self._active_entry = None
            return {'kind': 'clear', 'entry': None,
                    'key': None, 'changed': changed}
        entry = db[0]
        if not (isinstance(entry, list) and len(entry) >= 4):
            return {'kind': 'noise', 'entry': entry, 'key': None,
                    'changed': False}
        code = int(entry[1]) if isinstance(entry[1], (int, float)) else -1
        ts = float(entry[2]) if isinstance(entry[2], (int, float)) else 0.0
        key = (code, ts)
        if self._active_key == key:
            return {'kind': 'same', 'entry': entry, 'key': key,
                    'changed': False}
        self._active_key = key
        self._active_entry = entry
        return {'kind': 'new', 'entry': entry, 'key': key,
                'changed': True}
