#!/usr/bin/env python3
"""Re-run fusion + composer on every stored demonstration and report
what changes.  Non-destructive — READS the on-disk demos but does not
write them back.

Consumed by the §5 validation report for task 2026-08-01: what would
the new fusion rule produce on legacy stored intents?

Columns per demo:
  ops     — number of operations in the intent
  pos     — number of resolved positions (fusion.fuse_positions)
  anch    — number of anchor pick/place contacts after composer dedupe
  link    — number of derived_from_step_id linked steps
  rules   — set of fusion rules that fired
  lowconf — number of low-confidence positions
  label   — first two labels (for a taste of the label extractor)

Usage:
    python3 scripts/pbd_recompose_report.py > docs/pbd_recompose_findings.md
"""
from __future__ import annotations

import json
import os
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent
                       / 'src' / 'programming_by_demonstration'))

from programming_by_demonstration.fusion import fuse_positions
from programming_by_demonstration.program_composer import compose_program_draft
from programming_by_demonstration.schema import StructuredIntent


DEMOS_DIR = Path('/opt/cobot/demonstrations')


def _summarize(demo_path: Path):
    si_path = demo_path / 'structured_intent.json'
    if not si_path.is_file():
        return None
    with open(si_path) as f:
        raw = json.load(f)
    intent = StructuredIntent.from_dict(raw)
    ops_count = len(intent.operations)
    # Fusion has already been (may have been) applied on load — refuse
    # to be idempotent.
    positions = fuse_positions(intent)
    pos_count = len(positions)
    lowconf   = sum(1 for p in positions if p.low_confidence)
    rules     = sorted({p.fusion_rule for p in positions})
    labels    = [p.label for p in positions][:2]

    # Compose to see how many taught anchors vs. linked repeats.
    try:
        draft = compose_program_draft(intent, demo_id=demo_path.name)
        anchor_contacts = sum(1 for s in draft.steps
                              if s.get('position_role') in ('pick', 'place')
                              and not s.get('derived_from')
                              and not s.get('derived_from_step_id'))
        linked_repeats  = sum(1 for s in draft.steps
                              if s.get('derived_from_step_id'))
        routine_count   = len(draft.routines)
        routine_names   = [r.name for r in draft.routines]
    except Exception as e:
        anchor_contacts = -1
        linked_repeats  = -1
        routine_count   = -1
        routine_names   = []
    return {
        'demo':          demo_path.name,
        'ops':           ops_count,
        'pos':           pos_count,
        'anch':          anchor_contacts,
        'link':          linked_repeats,
        'lowconf':       lowconf,
        'rules':         rules,
        'labels':        labels,
        'routines':      routine_count,
        'routine_names': routine_names,
    }


def main():
    print('# PBD position-identity — re-compose findings')
    print()
    print(f'_Generated by `scripts/pbd_recompose_report.py` against '
          f'`{DEMOS_DIR}`_')
    print()

    if not DEMOS_DIR.is_dir():
        print('_(demonstrations dir not present on this host)_')
        return

    demos = sorted([d for d in DEMOS_DIR.iterdir() if d.is_dir()])
    rows = []
    for demo in demos:
        row = _summarize(demo)
        if row is None:
            continue
        rows.append(row)

    if not rows:
        print('_(no stored intents found)_')
        return

    print(f'**Demos processed:** {len(rows)}  ')
    over_merge   = sum(1 for r in rows if r['ops'] > 0 and r['pos'] < r['ops'])
    low_conf     = sum(1 for r in rows if r['lowconf'] > 0)
    with_link    = sum(1 for r in rows if r['link'] > 0)
    with_routine = sum(1 for r in rows if r.get('routines', 0) > 0)
    print(f'**Demos where fusion collapsed ≥1 slot pair (ops > positions):** {over_merge}  ')
    print(f'**Demos with a low-confidence position (chip fires in review):** {low_conf}  ')
    print(f'**Demos where composer emitted at least one linked repeat:** {with_link}  ')
    print(f'**Demos with a detected routine (2026-08-02 §1):** {with_routine}  ')
    print()

    print('## Per-demo summary')
    print()
    print('| demo | ops | positions | anchors | linked | low-conf | routines | fusion rules | first labels |')
    print('|------|----:|----------:|--------:|-------:|---------:|----------|--------------|--------------|')
    for r in rows:
        rules_s = ', '.join(r['rules']) or '—'
        labels_s = ', '.join(f'`{l}`' for l in r['labels']) or '—'
        routines_s = ', '.join(f'`{n}`' for n in r.get('routine_names', [])) or '—'
        print(f'| `{r["demo"]}` '
              f'| {r["ops"]} | {r["pos"]} '
              f'| {r["anch"]} | {r["link"]} | {r["lowconf"]} '
              f'| {routines_s} '
              f'| {rules_s} | {labels_s} |')

    # Bowl demos — flagged specifically because the task's §5 asked
    # for the three-bowl outcome.
    bowl_demos = [r for r in rows
                  if 'bowl' in ' '.join(r['labels']).lower()]
    if bowl_demos:
        print()
        print('## Bowl demos (task §5 spotlight)')
        print()
        for r in bowl_demos:
            print(f'- `{r["demo"]}`: {r["ops"]} op(s) → {r["pos"]} position(s), '
                  f'{r["anch"]} anchor(s), {r["link"]} linked repeat(s).  '
                  f'Rules: {", ".join(r["rules"])}')


if __name__ == '__main__':
    main()
