#!/usr/bin/env bash
# build_full_ledger.sh — concatenate docs/ledger/*.md in canonical order
# into build/full_ledger.md (gitignored). This is the "one big file" view
# for reading the whole ledger end-to-end without grep.
#
# Ordering rule:
#   1. era-01-*.md first (pre-addendum)
#   2. addendum-NN in numeric order (with -a/-b sub-letters after NN)
#
# Usage:  bash tools/build_full_ledger.sh
# Output: build/full_ledger.md
# Exit non-zero on any read failure.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
LEDGER_DIR="$REPO_ROOT/docs/ledger"
OUT_DIR="$REPO_ROOT/build"
OUT="$OUT_DIR/full_ledger.md"

mkdir -p "$OUT_DIR"

# Ordered file list: era-01 first, then addendum-NN (numeric, with -a/-b suffix).
ORDERED=()
for f in "$LEDGER_DIR"/era-01-*.md; do
  [[ -f "$f" ]] && ORDERED+=("$f")
done

# Numeric sort by NN in "addendum-NN[-suffix]-*.md" — python one-liner keeps
# 08a before 08b before 09 without POSIX-sort quirks.
while IFS= read -r f; do
  ORDERED+=("$f")
done < <(python3 - "$LEDGER_DIR" <<'PY'
import re, sys, glob
d = sys.argv[1]
files = glob.glob(f"{d}/addendum-*.md")
def key(p):
    m = re.search(r"addendum-(\d+)([a-z]?)", p)
    n = int(m.group(1))
    s = m.group(2) or ""
    return (n, s)
for p in sorted(files, key=key):
    print(p)
PY
)

# Emit a small banner + each file with an inline divider line.
{
  echo "# Cobot ledger — full concatenated view"
  echo
  echo "Generated by \`tools/build_full_ledger.sh\` from \`docs/ledger/\`."
  echo "This file is NOT the canonical source — it is a convenience concat."
  echo "The canonical source is the individual per-addendum files."
  echo
  echo "Order: era-01 first, then addendum-NN in numeric order."
  echo "File count: ${#ORDERED[@]}."
  echo
  echo "---"
  echo
  for f in "${ORDERED[@]}"; do
    printf '\n\n<!-- >>> %s -->\n\n' "$(basename "$f")"
    cat "$f"
    printf '\n\n<!-- <<< %s -->\n' "$(basename "$f")"
  done
} > "$OUT"

BYTES=$(wc -c < "$OUT")
LINES=$(wc -l < "$OUT")
printf 'wrote %s\n  bytes: %s\n  lines: %s\n  files concatenated: %s\n' \
  "$OUT" "$BYTES" "$LINES" "${#ORDERED[@]}"
